### ISSUE TITLE
App loading twice initially 

### ISSUE THREAD

**Issue by naveenkumarreddy** [johnpapa/angular2-tour-of-heroes#101]
Hi, I am new to angular 2 and I've upgraded the my application from RC4 to latest version and everything is working fine except the application loading twice initially by running with npm start command. I downloaded angular2-tour-of-heroes and run with JIT and same issue I found here as well. 

Could you please let me know is this issue or is it functionality.
Thanks in advance

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
