### ISSUE TITLE
AOT Broken again

### ISSUE THREAD

**Issue by oleduc** [johnpapa/angular2-tour-of-heroes#103]
Hi,

I'm not sure if I'm forgetting something but I keep getting this error when I try to use aot with this project:

```
> angular2-tour-of-heroes@0.1.0 start-aot /home/user/Apps/angular2-tour-of-heroes
> npm run aot && npm run rollup && gulp copy-aot && npm run lite


> angular2-tour-of-heroes@0.1.0 aot /home/user/Apps/angular2-tour-of-heroes
> ngc -p tsconfig-aot.json

Error: Error at /home/user/Apps/angular2-tour-of-heroes/app/main-aot.ts:3:36: Cannot find module '../aot/app/app.module.ngfactory'.
    at check (/home/user/Apps/angular2-tour-of-heroes/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Tsc.typeCheck (/home/user/Apps/angular2-tour-of-heroes/node_modules/@angular/tsc-wrapped/src/tsc.js:86:9)
    at /home/user/Apps/angular2-tour-of-heroes/node_modules/@angular/tsc-wrapped/src/main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
```

It is the only error that I get, after setting the project as such:
- Cloning
- $ npm i # No errors
- $ npm run start-aot

**Comment by tozlakonza** [comment]
Same issue here. Please is there any solution to this one?

**Comment by oleduc** [comment]
@tozlakonza I'm still not sure what is causing this, but I pined my typescript version to ~2.0.10 and I got it to compile.

**Comment by iskilber** [comment]
+1

**Comment by gabrielg-dev** [comment]
+1

npm i -> no errors
npm run start-aot 

> angular2-tour-of-heroes@0.1.0 start-aot <path>/toh
> npm run aot && npm run rollup && gulp copy-aot && npm run lite


> angular2-tour-of-heroes@0.1.0 aot <path>/toh
> ngc -p tsconfig-aot.json

Error at <path>/toh/node_modules/@angular/core/src/di/reflective_provider.d.ts:88:123: Cannot find name 'Map'.
Error at <path>/toh/node_modules/@angular/core/src/di/reflective_provider.d.ts:88:165: Cannot find name 'Map'.
Error at <path>/toh/node_modules/@angular/core/src/facade/lang.d.ts:12:17: Cannot find name 'Map'.
Error at <path>/toh/node_modules/@angular/core/src/facade/lang.d.ts:13:17: Cannot find name 'Set'.
Error at <path>/toh/node_modules/@angular/core/src/application_init.d.ts:16:18: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:24:15: Cannot find name 'Map'.
Error at <path>/toh/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:28:16: Cannot find name 'Map'.
Error at <path>/toh/node_modules/rxjs/Observable.d.ts:68:60: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/rxjs/Observable.d.ts:68:70: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/linker/compiler.d.ts:53:49: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/linker/compiler.d.ts:61:65: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/application_ref.d.ts:116:67: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/application_ref.d.ts:132:101: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/application_ref.d.ts:158:67: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/application_ref.d.ts:160:101: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/linker/ng_module_factory_loader.d.ts:14:34: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.d.ts:28:25: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/core/src/util/lang.d.ts:8:53: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/platform-browser/src/dom/dom_adapter.d.ts:97:42: Cannot find name 'Map'.
Error at <path>/toh/node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts:79:33: Cannot find name 'Map'.
Error at <path>/toh/node_modules/@angular/common/src/directives/ng_class.d.ts:46:34: Cannot find name 'Set'.
Error at <path>/toh/node_modules/@angular/common/src/pipes/async_pipe.d.ts:44:38: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts:22:37: Cannot find name 'Map'.
Error at <path>/toh/node_modules/@angular/http/src/headers.d.ts:52:59: Cannot find name 'Map'.
Error at <path>/toh/node_modules/@angular/http/src/url_search_params.d.ts:46:16: Cannot find name 'Map'.
Error at <path>/toh/node_modules/@angular/router/src/config.d.ts:307:62: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/router/src/router.d.ts:392:70: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/router/src/router.d.ts:414:59: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/router/src/interfaces.d.ts:78:99: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/router/src/interfaces.d.ts:157:109: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/router/src/interfaces.d.ts:227:115: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/router/src/interfaces.d.ts:297:89: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/router/src/interfaces.d.ts:367:50: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/@angular/router/src/utils/collection.d.ts:35:58: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/rxjs/operator/toPromise.d.ts:2:60: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/rxjs/operator/toPromise.d.ts:3:79: Cannot find name 'Promise'.
Error at <path>/toh/node_modules/rxjs/operator/toPromise.d.ts:3:89: Cannot find name 'Promise'.
Error at <path>/toh/app/hero.service.ts:14:16: Cannot find name 'Promise'.
Error at <path>/toh/app/hero.service.ts:18:13: Parameter 'response' implicitly has an 'any' type.
Error at <path>/toh/app/hero.service.ts:22:24: Cannot find name 'Promise'.
Error at <path>/toh/app/hero.service.ts:24:13: Parameter 'heroes' implicitly has an 'any' type.
Error at <path>/toh/app/hero.service.ts:24:35: Parameter 'hero' implicitly has an 'any' type.
Error at <path>/toh/app/hero.service.ts:27:21: Cannot find name 'Promise'.
Error at <path>/toh/app/hero.service.ts:34:23: Cannot find name 'Promise'.
Error at <path>/toh/app/hero.service.ts:47:29: Cannot find name 'Promise'.
Error at <path>/toh/app/hero.service.ts:55:13: Parameter 'res' implicitly has an 'any' type.
Error at <path>/toh/app/hero.service.ts:60:28: Cannot find name 'Promise'.
Error at <path>/toh/app/hero.service.ts:73:36: Cannot find name 'Promise'.
Error at <path>/toh/app/hero.service.ts:75:12: Cannot find name 'Promise'.
Error at <path>/toh/app/dashboard.component.ts:23:13: Parameter 'heroes' implicitly has an 'any' type.
Error at <path>/toh/app/heroes.component.ts:26:13: Parameter 'heroes' implicitly has an 'any' type.
Error at <path>/toh/app/heroes.component.ts:27:14: Parameter 'error' implicitly has an 'any' type.
Error at <path>/toh/app/heroes.component.ts:44:13: Parameter 'res' implicitly has an 'any' type.
Error at <path>/toh/app/heroes.component.ts:48:14: Parameter 'error' implicitly has an 'any' type.
Error at <path>/toh/app/hero-detail.component.ts:30:19: Parameter 'hero' implicitly has an 'any' type.
Error at <path>/toh/app/hero-detail.component.ts:41:15: Parameter 'hero' implicitly has an 'any' type.
Error at <path>/toh/app/hero-detail.component.ts:45:16: Parameter 'error' implicitly has an 'any' type.
Error at <path>/toh/app/main-aot.ts:3:36: Cannot find module '../aot/app/app.module.ngfactory'.
Error at <path>/toh/app/main-aot.ts:6:9: Parameter 'success' implicitly has an 'any' type.
Error at <path>/toh/app/main-aot.ts:7:10: Parameter 'error' implicitly has an 'any' type.

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "aot"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular2-tour-of-heroes@0.1.0 aot: `ngc -p tsconfig-aot.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-tour-of-heroes@0.1.0 aot script 'ngc -p tsconfig-aot.json'.
...

**Comment by lirongfei123** [comment]
me too, who can solve this? very thinks 
my node version is v7.0

**Comment by pp611** [comment]
Got the same errors @gabrielg-dev . Did the following command: (see  http://stackoverflow.com/questions/35660498/angular-2-cant-find-promise-map-set-and-iterator)
```
npm install --save-dev @types/core-js
```
the errors go away, but get tons of `The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten. See https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined for more information`, which seem not a problem.

**Comment by iJungleboy** [comment]
had same issues as @gabrielg-dev and also found the solution @pp611 - with the same "hundreds" of "this is undefined" messages.

**Comment by foobarfran** [comment]
Hi guys, I had the same issue and I've resolved it adding the es2015 lib in ```tsconfig-aot.json```:

```json
{
  "compilerOptions": {
    "lib": ["es2015", "dom"],
    ...
}

```

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
