### ISSUE TITLE
Failed to parse json error

### ISSUE THREAD

**Issue by cyuno** [johnpapa/angular2-tour-of-heroes#105]
node v6.9.2
npm v3.10.10
windows 10
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected  token '\u000' at 1:1
npm ERR! 
npm ERR!^
...
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just Javascript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tel the pacage author to fix their package.json file. JSON.parse

This is after cloning this repository and running npm i

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
