### ISSUE TITLE
No base href error

### ISSUE THREAD

**Issue by scottseeker** [johnpapa/angular2-tour-of-heroes#111]
When setting up routing I had to add the following or the app would not run:

import { APP_BASE_HREF } from '@angular/common';

then in the @NgModule annotation:
providers: [{provide: APP_BASE_HREF, useValue: '/'}]

**Comment by Ismaestro** [comment]
Do you have in your `index.html` this line in the head section?

`<base href="/">`

**Comment by scottseeker** [comment]
I was able to get around it.  I just wanted to point out that the tutorial does not mention this step.

I didn't use the index.html way of resolving, my solution is in the original comment.  Seems like what you said would be a bit simpler though.

**Comment by Ismaestro** [comment]
@scottseeker You are right. The tutorial never say anything about set the base href in the router section. You should read [this](https://angular.io/docs/ts/latest/guide/router.html#!#base-href).

:)

**Comment by johnpapa** [comment]
:)

closing since this was rewritten with the CLI
