### ISSUE TITLE
npm run start-aot fails

### ISSUE THREAD

**Issue by KevinBurton** [johnpapa/angular2-tour-of-heroes#112]
I tried to run 'npm run start-aot' and I get

Rs-MacBook-Pro:toh-aot rebeccaannburton$ nvm use 7.5.0
Now using node v7.5.0 (npm v4.1.2)
Rs-MacBook-Pro:toh-aot rebeccaannburton$ npm run start-aot

> angular2-tour-of-heroes@0.1.0 start-aot /Users/rebeccaannburton/Projects/toh-aot
> npm run aot && npm run rollup && gulp copy-aot && npm run lite

> angular2-tour-of-heroes@0.1.0 aot /Users/rebeccaannburton/Projects/toh-aot
> ngc -p tsconfig-aot.json

Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/di/reflective_provider.d.ts:87:123: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/di/reflective_provider.d.ts:87:165: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/facade/lang.d.ts:12:17: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/facade/lang.d.ts:13:17: Cannot find name 'Set'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/application_init.d.ts:16:18: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:24:15: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts:28:16: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/rxjs/Observable.d.ts:69:60: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/rxjs/Observable.d.ts:69:70: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/linker/compiler.d.ts:53:49: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/linker/compiler.d.ts:61:65: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/application_ref.d.ts:116:76: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/application_ref.d.ts:132:110: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/application_ref.d.ts:158:67: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/application_ref.d.ts:160:101: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/linker/ng_module_factory_loader.d.ts:14:34: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.d.ts:28:25: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/core/src/util/lang.d.ts:12:53: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/platform-browser/src/dom/dom_adapter.d.ts:97:42: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts:79:33: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/common/src/directives/ng_class.d.ts:48:34: Cannot find name 'Set'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/common/src/pipes/async_pipe.d.ts:44:38: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/platform-browser/src/dom/shared_styles_host.d.ts:11:30: Cannot find name 'Set'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/platform-browser/src/dom/shared_styles_host.d.ts:22:30: Cannot find name 'Set'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts:22:37: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/http/src/headers.d.ts:52:59: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/http/src/url_search_params.d.ts:46:16: Cannot find name 'Map'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/router/src/config.d.ts:307:85: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/router/src/router.d.ts:392:70: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/router/src/router.d.ts:414:59: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/router/src/interfaces.d.ts:78:99: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/router/src/interfaces.d.ts:157:109: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/router/src/interfaces.d.ts:227:115: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/router/src/interfaces.d.ts:297:89: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/router/src/interfaces.d.ts:367:50: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/@angular/router/src/utils/collection.d.ts:36:79: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/rxjs/operator/toPromise.d.ts:2:60: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/rxjs/operator/toPromise.d.ts:3:79: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/node_modules/rxjs/operator/toPromise.d.ts:3:89: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:14:16: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:18:13: Parameter 'response' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:22:24: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:24:13: Parameter 'heroes' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:24:35: Parameter 'hero' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:27:21: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:34:23: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:47:29: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:55:13: Parameter 'res' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:60:28: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:73:36: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero.service.ts:75:12: Cannot find name 'Promise'.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/dashboard.component.ts:23:13: Parameter 'heroes' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/heroes.component.ts:27:13: Parameter 'heroes' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/heroes.component.ts:28:14: Parameter 'error' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/heroes.component.ts:45:13: Parameter 'res' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/heroes.component.ts:49:14: Parameter 'error' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero-detail.component.ts:30:19: Parameter 'hero' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero-detail.component.ts:41:15: Parameter 'hero' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/hero-detail.component.ts:45:16: Parameter 'error' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/main-aot.ts:6:9: Parameter 'success' implicitly has an 'any' type.
Error at /Users/rebeccaannburton/Projects/toh-aot/app/main-aot.ts:7:10: Parameter 'error' implicitly has an 'any' type.

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/rebeccaannburton/.nvm/versions/node/v7.5.0/bin/node" "/Users/rebeccaannburton/.nvm/versions/node/v7.5.0/bin/npm" "run" "aot"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular2-tour-of-heroes@0.1.0 aot: `ngc -p tsconfig-aot.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-tour-of-heroes@0.1.0 aot script 'ngc -p tsconfig-aot.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-tour-of-heroes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ngc -p tsconfig-aot.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-tour-of-heroes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-tour-of-heroes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rebeccaannburton/Projects/toh-aot/npm-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/rebeccaannburton/.nvm/versions/node/v7.5.0/bin/node" "/Users/rebeccaannburton/.nvm/versions/node/v7.5.0/bin/npm" "run" "start-aot"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! angular2-tour-of-heroes@0.1.0 start-aot: `npm run aot && npm run rollup && gulp copy-aot && npm run lite`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-tour-of-heroes@0.1.0 start-aot script 'npm run aot && npm run rollup && gulp copy-aot && npm run lite'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-tour-of-heroes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run aot && npm run rollup && gulp copy-aot && npm run lite
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-tour-of-heroes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-tour-of-heroes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rebeccaannburton/Projects/toh-aot/npm-debug.log

I am not sure if it has to do with all of the errors (such as cannot find name 'Promise') Any suggestions on how I can get it to work. I am starting with this simple project to try and understand AOT.

**Comment by dverbovyi** [comment]
The same to me

**Comment by dattasid** [comment]
Getting same error. Windows 7, node 7.7.1, tsc 1.8 .

Edit : Did the npm install from 
 http://stackoverflow.com/questions/35660498/angular-2-cant-find-promise-map-set-and-iterator

and things are currently working.

**Comment by spock123** [comment]
Did you figure out what was wrong? Got precisely same issue on my build, going from RC4 to RC5/6/Final

**Comment by tuomasta** [comment]
Add "lib": ["es2015", "dom"] to tsconfig-aot.json

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
