### ISSUE TITLE
Failed to load dashboard.component.html

### ISSUE THREAD

**Issue by jfkquality** [johnpapa/angular2-tour-of-heroes#114]
In TOH Part 5, Routing, it says to put this for templateURL: 
"@Component({
  selector: 'my-dashboard',
  templateUrl: './dashboard.component.html',"

This resulted in "Failed to load dashboard.component.html". After a Google search it worked when I entered, "templateUrl: 'app/dashboard.component.html',"

Why doesn't it work as instructed?

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
