### ISSUE TITLE
Error: GET http://localhost:4200/styles.css

### ISSUE THREAD

**Issue by elekwent** [johnpapa/angular2-tour-of-heroes#115]
The last step in the [Routing Tutorial](https://angular.io/docs/ts/latest/tutorial/toh-pt5.html) is to apply a global style to the application. After following the instructions for doing so, I get an error in the browser: `GET http://localhost:4200/styles.css`. The app is being served using the CLI command: `ng serve` (if that makes any difference). The **styles.css** file is located at the default location where the CLI created it. Why can't the browser find the file?

### index.html
```
<head>
  <meta charset="utf-8">
  <title>AngularTourOfHeroes</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="styles.css">
</head>
```
### src directory (filtered for relevance)
```
.
├── app
│   ├── app-routing.module.ts
│   ├── app.component.css
│   ├── app.component.ts
│   ├── app.module.ts
│   ├── dashboard.component.css
│   ├── dashboard.component.html
│   ├── dashboard.component.ts
│   ├── hero-detail.component.css
│   ├── hero-detail.component.html
│   ├── hero-detail.component.ts
│   ├── hero.service.ts
│   ├── hero.ts
│   ├── heroes.component.css
│   ├── heroes.component.html
│   ├── heroes.component.ts
│   └── in-memory-data.service.ts
├── assets
├── favicon.ico
├── index.html
├── main.ts
└── styles.css
```

**Comment by rollthecoder** [comment]
same issu

**Comment by chriszrc** [comment]
Hi, ok, I had the same problem and the tutorial is wrong in one place. With the latest version of the angular cli, you no longer have to include the <link rel="stylesheet"...> in the index.html file. The cli will inject the contents automatically. So remove that line from the index.html and all should work. The files that get injected are specified in the .angular-cli.json file, and this works because the styles.css is already preconfigured there for you-

ref - https://github.com/angular/angular-cli/wiki/stories-global-styles

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI

**Comment by jofftiquez** [comment]
@chriszrc lol

**Comment by parthasarathysarathy** [comment]
#122 
#125

**Comment by Sachin124** [comment]
Okay Recently I fetched this problem I have very simple solution for solve this Issue , follow these steps:
**go to these directories  src-> app-> index.html** open the index.html and find
 **`<base href="your app name "> `change this to `<base href="/">`**

**Comment by siddharthasharma1986** [comment]
Hey , I have once query here. If we use # in place of "/". it is not able to find css. I am using scss.
