### ISSUE TITLE
angular + webpack -> core.es5.js bundling warning

### ISSUE THREAD

**Issue by lx93uv** [johnpapa/angular2-tour-of-heroes#118]
it's talking about https://angular.io/docs/ts/latest/guide/webpack.html tutorial, [here is my repo](https://github.com/lx93uv/angular-webpack-demo)

build completes ok except several warnings (`npm-start`)
```js
WARNING in ./~/@angular/core/@angular/core.es5.js
5870:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/@angular/core.es5.js
5886:15-102 Critical dependency: the request of a dependency is an expression
```

How to fix it?

**Comment by Albosonic** [comment]
I have this same problem.

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI

**Comment by matrumz** [comment]
@johnpapa 
Not everyone is using the CLI: I am one of those people who wants to build everything from the ground up as a learning experience. If this question could be answered, I'd be very appreciative. 

WARNING in ./node_modules/@angular/core/@angular/core.es5.js
5644:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@angular/core/@angular/core.es5.js
5660:15-102 Critical dependency: the request of a dependency is an expression

**Comment by joshuawilson** [comment]
Can you point to how it was rewritten in the CLI, so those of us that don't use can make the same change?

**Comment by johnpapa** [comment]
sure, check the commit history.

https://github.com/johnpapa/angular-tour-of-heroes/pull/120/files

**Comment by joshuawilson** [comment]
thanks
