### ISSUE TITLE
Read me is now out of date.

### ISSUE THREAD

**Issue by gravidThoughts** [johnpapa/angular2-tour-of-heroes#121]
No AOT based scripts in new version of package.json

**Comment by SanderElias** [comment]
@gravidThoughts. You are right, the whole readme is out of date, as the project is now using the CLI
If you build for production, AOT is activated. If you want to play with AOT during development, add `--aot` to the `ng serve ...` line in your package.json.

**Comment by johnpapa** [comment]
updated now
