### ISSUE TITLE
Problems deploying the app to Bluemix

### ISSUE THREAD

**Issue by FernandoDurier** [johnpapa/angular2-tour-of-heroes#122]
Hello, @johnpapa  !!
My name is Fernando. I am a software development intern and just started to work with angular 2 and angular cli. Before that I only have worked with backend applications (in Node.js) and Database Management (SQL and NoSQL).

I am having doubts on how to upload the tour-of-heroes in angular cli to Bluemix.
One way I found to upload it, was using a server.js file that is an express server that serves the app inside a dist folder. When I found this implementation, it was being used for heroku, I replicated every step and worked well. 
reference link -> https://medium.com/@ryanchenkie_40935/angular-cli-deployment-host-your-angular-2-app-on-heroku-3f266f13f352

It worked very well for my necessities. 
Link -> https://tour-of-heroes-nando777.mybluemix.net/dashboard

My doubts are:
1- Is that a valid solution ?
2- Is there any better solution ? If yes, how may I implement it ?

Thanks in Advance.
Best Wishes, Fernando Durier.

**Comment by johnpapa** [comment]
This is just the front end code, so yes, if you want to deploy it to the cloud I recommend using a server.js file using something like Express. Or use nginx.
