### ISSUE TITLE
How to deploy to Azure from Azure portal

### ISSUE THREAD

**Issue by kotpal** [johnpapa/angular2-tour-of-heroes#130]
https://johnpapa.net/deploy-angular-to-azure-vsts-angular-cli/ talks about how to deploy to Azure from VSTS. 

However, how can we deploy in Azure portal using git integration? 

I couldn't find one example so far that works. The examples show building and checking in all node_modules and dist to gi, and then deploy - which is not correct.  

Is there a working example of deploying TOH to Azure using Kudu/deployment script to perform the installation of modules and building on Azure itself?

**Comment by johnpapa** [comment]
better for stackoverflow
