### ISSUE TITLE
Breaking change in angular-in-memory-web-api breaks example for http request

### ISSUE THREAD

**Issue by the-mace** [johnpapa/angular2-tour-of-heroes#134]
This is no longer correct for the latest version of `angular-in-memory-web-api`:

`.then(response => response.json().data as Hero[])`

They made a breaking change and removed the "data" part, so the new line should be:

`.then(response => response.json() as Hero[])`

This appears in a couple places in the examples.

**Comment by ManfredLange** [comment]
I second that. 

Breaking changes as of version 0.5.0 of angular-in-memory-web-api. See [change log](https://github.com/angular/in-memory-web-api/blob/master/CHANGELOG.md). The "Tour of Heroes" tutorial's code should be updated accordingly.

As of writing (08 Oct 2017) at the end of step 6 the "Tour of Heroes" example is broken in that heroes are not listed, cannot be added, edited or deleted. This includes the [live example at Plunker](https://angular.io/generated/live-examples/toh-pt6/eplnkr.html) (link retrieved on 10 Oct 2017).

With the update in place the tutorial app seems to be working as expected.

**Comment by jlocans** [comment]
Uhh, this is second breaking change I come across in this tutorial. First one was that `angular-in-memory-web-api` now has to be installed seperately.

**Comment by johnpapa** [comment]
fixing for v6 today
