### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by matthewDDennis** [johnpapa/angular2-tour-of-heroes#24]
Runs fine in Firefox, but on IE11/win7

```
SCRIPT438: Object doesn't support property or method 'keys'
File: angular2.dev.js, Line: 4030, Column: 5
Object doesn't support property or method 'keys'
    Evaluating http://127.0.0.1:8080/src/app/bootstrap.js
    Error loading http://127.0.0.1:8080/src/app/bootstrap.js
```

**Comment by pkozlowski-opensource** [comment]
@matthewDDennis what is the version of ng2 that you've got in your setup? Could you please share with us what you've got in `File: angular2.dev.js, Line: 4030, Column: 5` on your machine?

**Comment by matthewDDennis** [comment]
Checked on my Win10 machine and it works on Edge.

**Comment by matthewDDennis** [comment]
Found the issue. I had to add es6-shim.js before system.js.  Strange, as I thought this was incorporated into system.js.

**Comment by pkozlowski-opensource** [comment]
Nope, system.js has only very minimal polyfill for ES5 things like `Array.indexOf` - if you want to run your code in a browser that doesn't support ES6 (like IE11) you need es6 polyfill (es6-shim.js is one of them)

**Comment by johnpapa** [comment]
yep. you need es6-shim for that.

**Comment by johnpapa** [comment]
updated in a recent commit
