### ISSUE TITLE
Refresh fails in child routes

### ISSUE THREAD

**Issue by sirajc** [johnpapa/angular2-tour-of-heroes#26]
Upon refreshing on routes like `http://127.0.0.1:8080/detail/11` - Refresh fails, Need to reload `http://127.0.0.1:8080/src` to make it work

**Comment by johnpapa** [comment]
works now. use lite-server

**Comment by pablodenadai** [comment]
How's `lite-server` different from let's say `connect`? Does it have a built-in URL rewrite for HTML5 location strategy?

**Comment by johnpapa** [comment]
yes
