### ISSUE TITLE
Back button on /detail/{id} view always takes you to the /heroes

### ISSUE THREAD

**Issue by mickeyvip** [johnpapa/angular2-tour-of-heroes#33]
The `back` button on `/detail` always takes you to the `/heroes` route, even if you arrive there from the root (dashboard).

I would assume that `back` will bring me to where I was before.

Thank you.

EDIT:

If I understand correctly, in order to do this, I need to import `ComponentInstruction` and `OnActivate`, implement `OnActivate` and get `next` + `prev` route representations.
I go to this part, but I cannot figure out how to convert `ComponentInstruction` to actual route.

`this._router.navigateByInstruction(prev)` does not work, since it expect `Instruction` with a property of type `ComponentInstruction`.

`this._router.navigateByUrl(prev.urlPath)` does OK when returning to `/heroes`, but throws an exception when returning to the dashboard with both `""` and `"/"`.

**Comment by johnpapa** [comment]
fixed now. i used history back

**Comment by mickeyvip** [comment]
Hi.

There is a problem with this solution. When one navigates directly to the `/details`, clicking `back` button has no effect, because newly opened window has no history.

Expected: navigates to default route (`/` or `/heroes`)
