### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by thol01** [johnpapa/angular2-tour-of-heroes#38]
- On index.html I needed to change the base tag to <base href="/">
- In app.component.ts templateUrl should be template and styleUrl should be styles.

Tried to do a pull request but it did not work.

Thanks for the amazing job you do on the docs! :)

/Thomas

**Comment by johnpapa** [comment]
thanks, this will all get updated very very soon :)

**Comment by hasan-assi** [comment]
can you please describe how the base tag should look like in the index file.
after having latest, the app doesn't work :(

**Comment by johnpapa** [comment]
the app is being updated today ... :)

**Comment by johnpapa** [comment]
app is updated
