### ISSUE TITLE
reflect-metadata shim is required

### ISSUE THREAD

**Issue by kostaad** [johnpapa/angular2-tour-of-heroes#39]
Hi, I pulled the source
npm i
npm run both
It looks like it got an error in loading
"
reflect-metadata shim is required when using class decorators
    Error loading http://localhost:3000/app/boot.js"

**Comment by pablodenadai** [comment]
See https://github.com/johnpapa/angular2-tour-of-heroes/issues/38.

The app is getting updated later on today.

**Comment by johnpapa** [comment]
should be good now
