### ISSUE TITLE
Error when loading app

### ISSUE THREAD

**Issue by garethdn** [johnpapa/angular2-tour-of-heroes#40]
After `npm install` and `npm run go`

![angular2error](https://cloud.githubusercontent.com/assets/2228940/11842044/f5e57e68-a3f8-11e5-91d9-7d5b8928dcba.PNG)

**Comment by johnpapa** [comment]
i just did a fresh clone, `npm i`, then `npm run go` and it worked for me.

Can you try clearing and trying again?

**Comment by garethdn** [comment]
Tried again and same thing. I had to add the following dependencies back into `package.json`

```
"es6-promise": "^3.0.2",
"es6-shim": "^0.33.13",
"reflect-metadata": "^0.1.2",
"rxjs": "^5.0.0-beta.0",
"zone.js": "^0.5.10"
```

**Comment by johnpapa** [comment]
odd

they are needed. but when i install angular2 they just come along for the ride

wanna make a PR for me?

**Comment by garethdn** [comment]
Hmm. I wonder is it down to differing `npm` versions and flattened dependencies?

I'm running Node v5.1.1 and NPM 3.3.12.

I might wait to see if anyone else has the issue before making a PR.

**Comment by johnpapa** [comment]
interesting. i am running node 0.10 and npm 2.14

gunna try node 4 and npm 3 now ...

**Comment by pablodenadai** [comment]
When in npm 3.x. Does it print a warning message in the terminal saying peerDeps aren't installed by default?

**Comment by garethdn** [comment]
@ghpabs Yep, I get unmet peer dependencies.

![npm-error](https://cloud.githubusercontent.com/assets/2228940/11844274/c7fa971a-a405-11e5-94d5-6b7d222a58cc.PNG)

**Comment by pablodenadai** [comment]
I believe they need to be installed/saved separately from angular2 when using npm 3.x. But I'll leave it for the repo's owner to decide what's right in this case. :-)

**Comment by mmykola** [comment]
I corrected so deleted folder node_modules/rxjs and reinstall rxjs@5.0.0-beta.0
 npm install es6-promise@^3.0.2 es6-shim@^0.33.3 reflect-metadata@0.1.2 rxjs@5.0.0-beta.0 zone.js@0.5.10

**Comment by pkozlowski-opensource** [comment]
> I believe they need to be installed/saved separately from angular2 when using npm 3.x.

Correct

> But I'll leave it for the repo's owner to decide what's right in this case. :-)

Yeh, those deps should be added to package.json of this app @johnpapa

**Comment by johnpapa** [comment]
yes, i was asking if someone wanted to make a PR.

but i'll do it :)

**Comment by johnpapa** [comment]
done

**Comment by schwarzb** [comment]
Following the tutorial, where does it indicate adding es6-promise@^3.0.2 is required for the Tour of Heroes to execute? Not having recent JavaScript experience and also being very new to Angular2, I'm not sure how or when  to update the dependencies if those instructions are not included in the tutorial.

The error I saw was:

>  "EXCEPTION: Error: Uncaught (in promise): TypeError: this._getParentElement(...) is null"          "Unhandled Promise rejection:" "this._getParentElement(...) is null" "; Zone:" "angular" "; Task:" "Promise.then" "; Value:" TypeError: this._getParentElement(...) is null   followed by                       Error: Uncaught (in promise): TypeError: this._getParentElement(...) is null

I modified the package.json to include the promises dependency; now I have this message:

> A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
> See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise
> and 
> "[CustomizableUI]" "Custom widget with id loop-button does not return a valid node" CustomizableUI.jsm:167

The browser is Firefox 38.4.0;  OS is CentOS 7.
npm version is 1.3.5;  node version is v0.10.42.

Do I need to also modify tsconfig.json?  Currently this is the content of that file from the tutorial:

tsconfig.json 
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
