### ISSUE TITLE
TOH from angular.io, doesn't recognize Promise

### ISSUE THREAD

**Issue by DocBradfordSoftware** [johnpapa/angular2-tour-of-heroes#43]
I was doing the step by step of the online Tutorial, and when I got to the point where it wanted me to add the Promise to the service, it no longer worked, both my Editor and the browser threw an error.

**Comment by johnpapa** [comment]
details?

**Comment by DocBradfordSoftware** [comment]
https://angular.io/docs/ts/latest/tutorial/toh-pt4.html
The Hero Service makes a promise.
getHeroes() {
  return Promise.resolve(HEROES);
}

Webstorm indicates the Promise is unknown and Firefox debug console throws and error.

**Comment by johnpapa** [comment]
Are you using the shims?

**Comment by DocBradfordSoftware** [comment]
I started with the Quickstart Tutorial and then copied that to Heroes. So that gives me these dependencies.
 "angular2": "2.0.0-beta.0",
    "systemjs": "0.19.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.10"

and these libraries.

``` html
<script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
  <script src="node_modules/systemjs/dist/system.src.js"></script>
  <script src="node_modules/rxjs/bundles/Rx.js"></script>
  <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
```

**Comment by DocBradfordSoftware** [comment]
Upgrading from Webstorm 11 to Webstorm 12, gives me a different error.
Now in app.component.ts, I get an error on this line.
this.heroes = this._heroService.getHeroes();

```
Assigned expression type Promise<Hero[]> is not assignable to type Hero[].
```

**Comment by DocBradfordSoftware** [comment]
It appears that upgrading from Webstorm 11 to 12 and moving to the next line in the tutorial, fixed the problem.
this._heroService.getHeroes().then(heroes => this.heroes = heroes);
Thanks, doc.

**Comment by johnpapa** [comment]
np :)
