### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by netlander** [johnpapa/angular2-tour-of-heroes#48]
npm ERR! peerinvalid The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.1 wants reflect-metadata@0.1.2

**Comment by johnpapa** [comment]
Thank you for rephrasing your comment.

Angular 2 has a peer dep on reflect metadata. This can be fixed by pinning to 0.1.2. I just updated the package to do so, tho this is a workaround IMO.

cc // @igorminar @wardbell

**Comment by netlander** [comment]
A bit too hasty on the comment but yes it is about reflect metadata 0.1.3. Once the ^ is removed the error goes away.

**Comment by failpunk** [comment]
I get the following errors...

```
npm ERR! peerinvalid The package rxjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.1 wants rxjs@5.0.0-beta.0
```

Changing the following does the trick...

From:
`"rxjs": "^5.0.0-beta.0",`

To:
`"rxjs": "5.0.0-beta.0",`

**Comment by helix46** [comment]
And now
The package zone.js@0.5.11 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.0 wants zone.js@0.5.10

Changing 
"zone.js": "^0.5.10"
to "zone.js": "0.5.10"
fixes it

**Comment by johnpapa** [comment]
old error, now updated to beta 3 and zone 0.5.11

**Comment by mik-laj** [comment]
Installing a new version of npm/node.js also solves this problem. :-)
