### ISSUE TITLE
npm install fail due to zone.js@0.5.11

### ISSUE THREAD

**Issue by ghoullier** [johnpapa/angular2-tour-of-heroes#54]
Hi!

Last angular (beta3) requires zone.js@0.5.11 but this version seems not working correctly 

``` console
> zone.js@0.5.11 postinstall ~/temporary/angular2-tour-of-heroes/node_modules/zone.js
> tsd install

sh: 1: tsd: not found

[...]

npm ERR! node v4.2.3
npm ERR! npm  v2.14.17
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! zone.js@0.5.11 postinstall: `tsd install`
npm ERR! spawn ENOENT
```

**Comment by james-ingold** [comment]
I think this is an issue with the angular beta 3 npm package, you can get around it by installing the zone.js dependency in front of angular:
npm install zone.js@0.5.11 --save-dev
npm install angular2 --save-dev

**Comment by johnpapa** [comment]
zone 0.5.11 is in the package. what are you proposing?

**Comment by johnpapa** [comment]
I just re-cloned this and ran `npm i` and it installs with no errors.

**Comment by kootenpv** [comment]
I had the same issue.

```
npm install zone.js@0.5.11 --save-dev
npm install angular2 --save-dev
npm i
```

worked after trying everything; even upgrading to latest node/npm.

**Comment by chundemer** [comment]
Just in case someone else runs into this issue.. For me, I did not have tsd installed globally.

**Comment by Kinnardian** [comment]
Got the same problem. Did an `npm install tsd`. Worked.

**Comment by zevero** [comment]
@Kinnardian thanks!

**Comment by ragmha** [comment]
@Kinnardian :+1:

**Comment by msegers** [comment]
@chundemer danke

**Comment by flacle** [comment]
@Kinnardian thanks mate, worked like a charm :)

**Comment by domfarolino** [comment]
Yep, I had to `sudo npm install tsd`

**Comment by zqylur** [comment]
@Kinnardian, thank you sir, that fixed it for me as well.
