### ISSUE TITLE
Bundle all Js

### ISSUE THREAD

**Issue by Talento90** [johnpapa/angular2-tour-of-heroes#55]
There is any simple way to concat all Js files in a single one? 

Thank you!

**Comment by vlad0** [comment]
You can use gulp.js for such modifications which is pretty straightforward

**Comment by mmykola** [comment]
Hi, I used gulp.js with https://github.com/systemjs/builder

**Comment by iJungleboy** [comment]
This will probably be handled by Angular CLI, but requires to move to webpack - see #83
