### ISSUE TITLE
[Still] Doesn't Work in IE

### ISSUE THREAD

**Issue by GregWoods** [johnpapa/angular2-tour-of-heroes#56]
#24 was closed. The comments don't help. I suspect the person that got it working did something else which they didn't reveal.

TOH didn't work for IE11 in its Beta0 guise, and doesn't work in Beta6. 

The plunker linked to from the angular.io Tour of Heroes first page doesn't work, and it clearly has the es6 shim loaded (which is the claimed solution in issue #24)
Pretty sure it's not me being stupid. Instructions followed exactly, and the code claims to support IE

```
    <!-- 1. Load libraries -->
    <!-- IE required polyfills, in this exact order -->
    <script src="node_modules/es6-shim/es6-shim.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>

    <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.js"></script>
    <script src="node_modules/angular2/bundles/angular2.dev.js"></script>
```

All files loading, no 404s
Tried es6-shim 0.33.13 as specified by angular
Also forced Angular to use 0.34.4 but still no luck

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI

uncomment the polyfills for IE
