### ISSUE TITLE
add gulp to TOH

### ISSUE THREAD

**Issue by matthiasbalke** [johnpapa/angular2-tour-of-heroes#59]
As everybody uses gulp today it would be straight forward to add gulp to the TOH tutorial. This would take it one step further and demonstrate how to bundle the app production ready.

**Comment by jonbiere** [comment]
Have a look at this blog its been done already.
http://blog.scottlogic.com/2015/12/24/creating-an-angular-2-build.html

**Comment by ms-denver** [comment]
When I follow the tutorial above I get an error 'Cannot find name 'Promise', 'Cannot find name'Set', Cannot find name 'Map'. How do I tell typescript compiler to reference the angular2 files?

**Comment by jonbiere** [comment]
jdiapps you have to add a typings.d.ts file in with your project source. 
Mine just looks like this and references the installed typings.

`/// <reference path="../typings/main.d.ts" />`

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
