### ISSUE TITLE
Methods in HeroService

### ISSUE THREAD

**Issue by schwarzb** [johnpapa/angular2-tour-of-heroes#60]
HeroesComponent calls getHeroes() from HeroService.  There is no "getHeroes()" method in HeroService.  HeroService does have a method getHero(id: number).

**Comment by ercpereda** [comment]
The service contains that method

```
@Injectable()
export class HeroService {
  .......
  getHero(id: number) {
    return Promise.resolve(HEROES).then(
      heroes => heroes.filter(hero => hero.id === id)[0]
    );
  }
}
```

**Comment by schwarzb** [comment]
Thank you;  I did see that later.  I find the tutorial challenging to follow. Often we are told to execute a command or
add lines of code but not where we should be ( which directory or which class even ) when taking these actions.
It helps when the final code is included in the tutorial; but this did not happen for many files in the Service and Routes lessons.
 I’m still trying to get those lessons to execute without success.

Thank you for your reply,

Betty

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
