### ISSUE TITLE
System is not defined error

### ISSUE THREAD

**Issue by thefeldkircher** [johnpapa/angular2-tour-of-heroes#62]
Hi
This app works fine using npm start, however whenever I try to call it through localhost or file:// I get a **System is not defined** error, and all resources are not loaded.

I have also used the quickstart clone here https://github.com/angular/quickstart
I have completed the tutorial on the official angular 2 website using above as a template, in all cases I get the same error outside of npm start. Not a single version will run.

Strangely, I did the 5 Min Quickstart tutorial from the angular 2 website and this is OK in and outside of npm start, I can run the 5 Min index.html inside a browser from a file:// or localhost reference.

Any help would be appreciated, I really want to get to grips with ng2.

Further investigation shows no resources are being loaded:
![links](https://cloud.githubusercontent.com/assets/10677364/15108023/6e4b0d34-15cb-11e6-9f79-fd4b3326559f.jpg)

Best Regards

Steve

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
