### ISSUE TITLE
It remains ever in "Loading..." mode

### ISSUE THREAD

**Issue by Aerendir** [johnpapa/angular2-tour-of-heroes#67]
Hi, I'm following the tutorial "Tour of heros" and in the [first page of the tutorial](https://angular.io/docs/ts/latest/tutorial/) there is a link to the [Tour of heroes](https://angular.io/resources/live-examples/toh-6/ts/plnkr.html) demo.

I'm a beginner starting to learn Angular, so I don't know if this is the correct behavior and I have to wait, but the application ever shows "Loading..." and never loads...

What can I do to test the demo?

**Comment by anirudh1800** [comment]
I'm also getting same loading problem for "Tour of Heroes" tutorial from https://angular.io/docs/ts/latest/tutorial/toh-pt6.html and plunker live example shown in the tutorial, also seems to be facing the same problem.

**Comment by ghost** [comment]
If it says "Loading..." something with ng2 went wrong/is missing... did you check out the F12 Tools? Did you intstall the node_modules specified in package.json via "npm i" ?

**Comment by anirudh1800** [comment]
I got it working now. Please update your package.json to latest rc4 version given in the tutorial. Also, router-deprecated is no longer used.
