### ISSUE TITLE
Has the tutorial changed in the last few days?

### ISSUE THREAD

**Issue by FrancescoMussi** [johnpapa/angular2-tour-of-heroes#71]
Hello!

Nice tutorial.
Just a question. I followed that until the Service chapter and everything was working properly.
I stop for 4-5 days and restart today with the chapter about Routing.
And something seems pretty different.

Now there is an app.module that before there wasn't..

Before my main.ts was looking like this:

```
import { bootstrap }    from '@angular/platform-browser-dynamic';
import { AppComponent } from './app.component';

bootstrap(AppComponent);
```

But in the tutorial now it looks like this:

```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';

platformBrowserDynamic().bootstrapModule(AppModule);
```

I am not going crazy right? There has been some recent changes?

As a matter of fact there is no app.module.ts file here..

Just the tutorial changed or also Angular 2?

Are we good to go with the new version or there will be more changes?

**Comment by attilacsanyi** [comment]
Definitely @francesco RC5 is out: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc5-2016-08-09

**Comment by FrancescoMussi** [comment]
Ok thanks..
Can I ask you one thing?
I know is not the proper place.
But how is the situation with Angular2? 
Is still in beta?
Can we use it for production project?
Thanks!

**Comment by attilacsanyi** [comment]
As i mentioned it is already release candidate version 5,so close to final release, estimated this year. For new project it was suggested to be safe enough as the core of the framework is not going to change further. Please follow http://angular.io for more details.

**Comment by FrancescoMussi** [comment]
Ok thanks!
