### ISSUE TITLE
Template expressions interpolate to empty values

### ISSUE THREAD

**Issue by kayasky** [johnpapa/angular2-tour-of-heroes#72]
After just completing the first step (Show our Hero) in the tutorial of modifying the `AppComponent` and the `template`, I noticed that the `{{title}}` and `{{hero}}` template vars get compiled to empty values instead of the expected values.

I just see the word "details" on the page, without any errors in the console:

<img width="231" alt="screen shot 2016-08-20 at 2 42 14 pm" src="https://cloud.githubusercontent.com/assets/3538762/17833199/6306487a-66e4-11e6-847d-451f9173d56e.png">

Everything is as-is from the Quickstart repo except my app.component.ts file which looks like this:

```
import { Component } from '@angular/core';

@Component({
    selector: 'my-app',
    template: '<h1>{{title}}</h1><h2>{{hero}} details</h2>'
})

export class AppComponent {
  title: 'Tour of Heroes';
  hero: 'Windstorm';
}
```

**Comment by kevineo** [comment]
I encountered this too and fixed it by adding 'hero' property into the app component like this:

```
export class AppComponent {
  title = 'Tour of Heroes';
  hero: Hero = {
    id: 1,
    name: 'Windstorm'
  };
}
```

Try this and see if it works.

**Comment by johnpapa** [comment]
In your comment, notice the colons `:` ...

```
export class AppComponent {
  title: 'Tour of Heroes';
  hero: 'Windstorm';
}
```

The colon tells typescript you will follow with the type. I think you instead wanted 

```
export class AppComponent {
  title = 'Tour of Heroes';
  hero = 'Windstorm';
}
```

**Comment by kayasky** [comment]
@johnpapa thanks! That fixes it.
