### ISSUE TITLE
TOH-6 Examples 'BAD FILENAME:' Problem 

### ISSUE THREAD

**Issue by zaferayan** [johnpapa/angular2-tour-of-heroes#76]
In 6th tutorial [add, delete, edit section](https://angular.io/docs/ts/latest/tutorial/toh-pt6.html#!#add-edit-delete) code examples has error like this:
`BAD FILENAME: ../../../_fragments/toh-6/ts/app/hero.service-post.ts.md   Current path: docs,ts,latest,tutorial,toh-pt6 PathToDocs: ../../../`

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
