### ISSUE TITLE
Get below error 

### ISSUE THREAD

**Issue by mkscala** [johnpapa/angular2-tour-of-heroes#77]
toh$ npm install
npm WARN package.json angular2-tour-of-heroes@0.1.0 No repository field.
npm WARN package.json angular2-tour-of-heroes@0.1.0 No license field.

> angular2-tour-of-heroes@0.1.0 postinstall /home/mkmani/toh
> typings install

typings WARN deprecated 8/30/2016: "registry:dt/node#6.0.0+20160807145350" is deprecated (updated, replaced or removed)
typings WARN deprecated 7/25/2016: "registry:dt/core-js#0.0.0+20160602141332" is deprecated (updated, replaced or removed)

├── angular-protractor (global)
├── core-js (global)
├── jasmine (global)
├── node (global)
└── selenium-webdriver (global)

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/home/mkmani/.nvm/versions/node/v4.4.5/bin/node" "/home/mkmani/.nvm/versions/node/v4.4.5/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/http@2.0.0-rc.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2-in-memory-web-api@0.0.18 wants @angular/http@2.0.0-rc.6

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mkmani/toh/npm-debug.log

**Comment by mkscala** [comment]
After install latest node and npm get below error
**$ nvm install node
Now using node v6.5.0 (npm v3.10.3)**

> angular2-tour-of-heroes@0.1.0 postinstall /home/mkmani/toh
> typings install

typings WARN deprecated 8/30/2016: "registry:dt/node#6.0.0+20160807145350" is deprecated (updated, replaced or removed)
typings WARN deprecated 7/25/2016: "registry:dt/core-js#0.0.0+20160602141332" is deprecated (updated, replaced or removed)

├── angular-protractor (global)
├── core-js (global)
├── jasmine (global)
├── node (global)
└── selenium-webdriver (global)

npm WARN optional Skipping failed optional dependency /lite-server/browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/core@2.0.0-rc.6 requires a peer of rxjs@5.0.0-beta.11 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.18 requires a peer of @angular/http@2.0.0-rc.6 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.18 requires a peer of rxjs@5.0.0-beta.11 but none was installed.
npm WARN angular2-tour-of-heroes@0.1.0 No repository field.
npm WARN angular2-tour-of-heroes@0.1.0 No license field.

**# mkmani@sparkcluster-4298:~/toh$ npm start**

> angular2-tour-of-heroes@0.1.0 start /home/mkmani/toh
> tsc && concurrently "npm run tsc:w" "npm run lite"

node_modules/@angular/forms/src/directives.d.ts(26,46): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives.d.ts(27,50): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives.d.ts(28,50): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives.d.ts(46,39): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives.d.ts(50,48): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.d.ts(12,18): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/form_providers.d.ts(13,38): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/forms/src/form_providers.d.ts(18,47): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/router/src/common_router_providers.d.ts(9,26): error TS2305: Module '"/home/mkmani/toh/node_modules/@angular/core/index"' has no exported member 'ComponentResolver'.
node_modules/@angular/router/src/config.d.ts(481,17): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/router/src/router.d.ts(14,10): error TS2305: Module '"/home/mkmani/toh/node_modules/@angular/core/index"' has no exported member 'ComponentResolver'.
node_modules/@angular/router/src/router.d.ts(125,36): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/router/src/router_state.d.ts(43,75): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/router/src/router_state.d.ts(68,16): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
node_modules/@angular/router/src/router_state.d.ts(101,16): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/home/mkmani/.nvm/versions/node/v6.5.0/bin/node" "/home/mkmani/.nvm/versions/node/v6.5.0/bin/npm" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-tour-of-heroes@0.1.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular2-tour-of-heroes@0.1.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-tour-of-heroes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run lite"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-tour-of-heroes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-tour-of-heroes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mkmani/toh/npm-debug.log

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
