### ISSUE TITLE
The Hero Editor: Issue with Multi-Line Template Strings

### ISSUE THREAD

**Issue by kevineo** [johnpapa/angular2-tour-of-heroes#78]
I am new to Angular 2. While attempting [part 2](https://angular.io/docs/ts/latest/tutorial/toh-pt1.html) of the challenge I encountered an issue with the multi-line templating for this tutorial. The tutorial instructs us to write the template as follows:

```
@Component({
  selector: 'my-app',
  template: 
    <h1>{{title}}</h1>
    <h2>{{hero.name}} details!</h2>
    <div><label>id: </label>{{hero.id}}</div>
    <div>
      <label>name: </label>
      <input [(ngModel)]="hero.name" placeholder="name">
    </div>

})
```

Which in turn throws an error on VS Code (see screenshot below) and Chrome is unable to read the template.

![screen shot 2016-09-04 at 10 07 49 pm](https://cloud.githubusercontent.com/assets/16037146/18231444/759d779c-72ec-11e6-80aa-ef0ef98b9aca.png)

However when I rewrite it back in its original format (as a single-line template string). It works fine:

`@Component({
  selector: 'my-app',
  template: 
            "<h1>{{title}}</h1><h2>{{hero.name}} details!</h2><div><label>id: </label>{{hero.id}}</div><div><label>name: </label><input [(ngModel)]='hero.name' placeholder='name'></div>"
})`

Am I missing something here? I followed the Quickstart tutorial word-for-word. I would like to learn how to use multi-line template strings in the future.

Thanks.

**Comment by johnpapa** [comment]
There maybe a type in this editor, but did you add the back ticks around the template?

```
@Component({
  selector: 'my-app',
  template: `
    <h1>{{title}}</h1>
    <h2>{{hero.name}} details!</h2>
    <div><label>id: </label>{{hero.id}}</div>
    <div>
      <label>name: </label>
      <input [(ngModel)]="hero.name" placeholder="name">
    </div>
    `
})
```

back-ticks can be used for multi line strings in ES6 and TypeScript

**Comment by kevineo** [comment]
Didn't notice the back ticks! The back ticks definitely made the difference - and it works. Thanks!
