### ISSUE TITLE
Typo at code summary of Multiple Components Chapter

### ISSUE THREAD

**Issue by kevineo** [johnpapa/angular2-tour-of-heroes#79]
In the summary segment, code written for app/app.module.ts reads:

`import { HeroDetailComponent } from './hero-detail.component';`

Which will throw an error. It is missing the right directory. It should instead be written as:

`import { HeroDetailComponent } from './app.hero-detail.component';
`

**Comment by johnpapa** [comment]
where?

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
