### ISSUE TITLE
Forget create method

### ISSUE THREAD

**Issue by FrancescoMussi** [johnpapa/angular2-tour-of-heroes#80]
Hello.
Great tutorial!

Just one thing: In the chapter 7, when creating a new hero, the create method of the hero service is not shown. 

There is the code for the add button
The code for the add method of the heroes component
But not the code for the create method of the service

**Comment by johnpapa** [comment]
ah, please put comments about the official ToH on the angular repo. We look there for the issues and our team fixes them there. 

This repo is my own playground for ToH :)
