### ISSUE TITLE
Properties: equal sign vs colon

### ISSUE THREAD

**Issue by denisemauldin** [johnpapa/angular2-tour-of-heroes#84]
Hi all,

I've never used Typescript before, so perhaps this is a super newbie question, but I've had some problems understanding the equal sign vs the colon in the tutorial.  At the end of toh-pt2.html, the class looks like this:

```
export class AppComponent {
  title = 'Tour of Heroes';
  heroes = HEROES;
  selectedHero: Hero;
  onSelect(hero: Hero): void {
    this.selectedHero = hero;
  }
}
```

The tutorial does not explain what the difference is between an equal sign and a colon in the property assignment, but the code doesn't work if you switch them (ie: heroes: HEROES; or selectedHero = Hero;).  "Let’s create a public property in AppComponent that exposes the heroes for binding." is how "heros = HEROES;" is described. "We no longer need the static hero property of the AppComponent. Replace it with this simple selectedHero property:" is how "selectedHero: Hero;" is defined.  

It seems like we're using selectedHero as an object property, but that title and heroes are properties in the object? When do we need to use object properties(:) versus properties(=)?

**Comment by dpurp** [comment]
The equals sign (`=`) is used for assignment (like JavaScript).  Whereas, the colon (`:`) is a TypeScript construct used to declare the type.

The code above uses a mix of explicit and inferred typing.  

If this were being fully explicit, the line:

``` typescript
title = 'Tour of Heroes';
```

would be written:

``` typescript
title: string = 'Tour of Heroes';
```

**Comment by johnpapa** [comment]
thanks

**Comment by slimlime** [comment]
This is fine until you run into a custom object that you are constructing 🤣 
```ts
interface ISomeInterfaceForMyObjectDemo {
    myValue: number
}
```
and then the created object, assigning the values based on the interface/defined-object properties.
```ts
const myNewObject: ISomeInterfaceForMyObjectDemo = { 
    myValue: 9001
}
// 9001
console.log(myNewObject.myValue);
```
