### ISSUE TITLE
Folder Structure to Follow Angular Guidelines

### ISSUE THREAD

**Issue by dillonbailey** [johnpapa/angular2-tour-of-heroes#85]
@johnpapa what are your thoughts on the file structure inside of app changing to fit the guidelines at https://angular.io/styleguide?

I'd be open to giving this a crack if it would be helpful.

**Comment by johnpapa** [comment]
normally i would ... but right now we are retrofitting ToH and I'm not sure we want this repo to get ahead of it.

But when the time is right, I will make it happen. Til then, check out my `event-view`  repo :)

**Comment by dillonbailey** [comment]
@johnpapa thanks heaps I've just jumped over to https://github.com/johnpapa/event-view - SUPER helpful! 👍 

Thank you again. DB
