### ISSUE TITLE
Direct links to details view do not work with default lite-server config

### ISSUE THREAD

**Issue by Zenith-One** [johnpapa/angular2-tour-of-heroes#86]
I spent a great deal of time trying to figure out how I'd broken my ToH app, as I kept getting a ton of 404 errors and `Uncaught ReferenceError: System is not defined`. After a while, I realized that the error only happened when BrowserSync would refresh in details view. 

lite-server is designed to tackle this specific sort of issue, but the Angular 2 QuickStart repo doesn't include a bs-config file to set that up.

Considering that the routing section of the ToH tutorial sites deep linking specifically, I feel like it might be a good idea to either mention this as a known issue during the tutorial, or to advise creating a bs-config file with the appropriate configs set.

Another possible, if less pretty, solution would be to suggest using the HashLocationStrategy. Of the two, I recommend the first.

**Comment by johnpapa** [comment]
it works in this repo, could you open an issue on the repo where it is not working?

that would be very helpful, thanks!
