### ISSUE TITLE
Error on npm run lite

### ISSUE THREAD

**Issue by algotastic** [johnpapa/angular2-tour-of-heroes#88]
Tried running for the first time today. Please let me know if there are is any additional info I can provide.

> $ npm start
> 
> > angular2-tour-of-heroes@0.1.0 start D:\Users\Adam\dev\toh
> [npm-debug.log.txt](https://github.com/johnpapa/angular2-tour-of-heroes/files/518389/npm-debug.log.txt)
> 
> > gulp copy-jit && concurrently "npm run tsc:w" "npm run lite"
> 
> [10:33:17] Using gulpfile D:\Users\Adam\dev\toh\gulpfile.js
> [10:33:17] Starting 'clean'...
> [10:33:17] clean
> [10:33:17] Finished 'clean' after 9.64 ms
> [10:33:17] Starting 'copy-jit'...
> [10:33:17] copy jit
> [10:33:17] Finished 'copy-jit' after 30 ms
>  Error occured when executing command: npm run lite
>  Error: spawn /bin/bash ENOENT
>      at exports._errnoException (util.js:907:11)
>      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
>      at onErrorNT (internal/child_process.js:344:16)
>      at nextTickCallbackWith2Args (node.js:442:9)
>      at process._tickCallback (node.js:356:17)
>      at Function.Module.runMain (module.js:443:11)
>      at startup (node.js:139:18)
>      at node.js:974:3
>  Error occured when executing command: npm run lite
>  Error: spawn /bin/bash ENOENT
>      at exports._errnoException (util.js:907:11)
>      at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
>      at onErrorNT (internal/child_process.js:344:16)
>      at nextTickCallbackWith2Args (node.js:442:9)
>      at process._tickCallback (node.js:356:17)
>      at Function.Module.runMain (module.js:443:11)
>      at startup (node.js:139:18)
>      at node.js:974:3
> [1] npm run lite exited with code -4058
> 
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
> npm ERR! node v4.6.0
> npm ERR! npm  v2.15.9
> npm ERR! code ELIFECYCLE
> npm ERR! angular2-tour-of-heroes@0.1.0 start: `gulp copy-jit && concurrently "npm run tsc:w" "npm run lite"`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the angular2-tour-of-heroes@0.1.0 start script 'gulp copy-jit && concurrently "npm run tsc:w" "npm run lite" '.
> npm ERR! This is most likely a problem with the angular2-tour-of-heroes package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     gulp copy-jit && concurrently "npm run tsc:w" "npm run lite"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs angular2-tour-of-heroes
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls angular2-tour-of-heroes
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\Users\Adam\dev\toh\npm-debug.log

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
