### ISSUE TITLE
Question:  hero search only works once, have to refresh the page.

### ISSUE THREAD

**Issue by daBishMan** [johnpapa/angular2-tour-of-heroes#89]
I am using your example about the hero-search component, what I am trying to do is using for like a typeahead example.   When I start my simple example the search/typeahead works fine.   what I do on the click is populate the input box with the values selected from the values that came back, not direct to another page.

Now if I delete the text in the input box and want to try to do another search it does not work, If I refresh the page it works.  

What I need to make it work with the ability to do more than one search at a time.  

You can look at my repo called https://github.com/daBishMan/ng2-observables if you want to see what I am doing wrong. 

Any help you can provide is greatly appreciated.

**Comment by johnpapa** [comment]
please post to the official angular.io repo so we can hit this question there.
