### ISSUE TITLE
npm install broken after update to 2.1

### ISSUE THREAD

**Issue by mstarrrsui** [johnpapa/angular2-tour-of-heroes#90]
npm ERR! peerinvalid The package @angular/compiler@2.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/compiler-cli@0.6.4 wants @angular/compiler@2.0.2
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.1.0 wants @angular/compiler@2.1.0
npm ERR! peerinvalid Peer @angular/platform-server@2.1.0 wants @angular/compiler@2.1.0
npm ERR! peerinvalid Peer @angular/upgrade@2.1.0 wants @angular/compiler@2.1.0

**Comment by johnpapa** [comment]
thanks.

try now. i updated the compiler cli one to 2.1.0, see if that does it

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
