### ISSUE TITLE
Trying to use express server to serve angular2 application as static content not working

### ISSUE THREAD

**Issue by maheshk172** [johnpapa/angular2-tour-of-heroes#91]
Hi,

I am trying to create angular2 application with express server.  The applications loads fine but it is not able to resolve the html paths from express server.

Please find the code
https://github.com/SomethingWhichWorks/typescript-express-angular-module

I tried simple todo's app on **'master'** branch and tried same on 'angular2-tour-of-heros' on **'alignment-with-angular-2.1.0'** branch.

But in both cases, the html content is not found.
zone.js:1274GET http://localhost:3000/app/hero-search.component.html 404 (Not Found)
Failed to load http://localhost:3000/app/hero-search.component.html
zone.js:1274GET http://localhost:3000/app/dashboard.component.html 404 (Not Found)
zone.js:1274GET http://localhost:3000/app/heroes.component.html 404 (Not Found)
zone.js:1274GET http://localhost:3000/app/hero-detail.component.html 404 (Not Found)
zone.js:1274 GET http://localhost:3000/app/app.component.css 404 (Not Found)

Could you please advise on this.

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
