### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by pptyasar** [johnpapa/angular2-tour-of-heroes#96]
argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! heroes@0.1.0 start: `gulp copy-jit && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the heroes@0.1.0 start script 'gulp copy-jit && concurrently "npm run tsc:w" "npm run lite" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the heroes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp copy-jit && concurrently "npm run tsc:w" "npm run lite" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs heroes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls heroes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Web/angular/heroes/npm-debug.log

**Comment by johnpapa** [comment]
closing since this was rewritten with the CLI
