### ISSUE TITLE
system-config.js Not Found

### ISSUE THREAD

**Issue by MojtabaGhavidel** [johnpapa/angular2-tour-of-heroes#98]
I get this error in consol :

Failed to load resource: the server responded with a status of 404 (Not Found)
zone.js:232 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:8000/system-config.js

**Comment by FrancescoMussi** [comment]
Same situation here:
![screen shot 2016-11-10 at 20 05 06](https://cloud.githubusercontent.com/assets/5312907/20190276/0513578e-a781-11e6-8d8b-bc38202723f8.png)

**Comment by hpphat92** [comment]
Check changing or this MR:
https://github.com/johnpapa/angular2-tour-of-heroes/pull/104

**Comment by MojtabaGhavidel** [comment]
Thanks but solved it with some change on config files that i don't remember atm
